blank_issues_enabled: false
contact_links:
  - name: ğŸ“ Documentation
    url: https://github.com/nanoexpress/docs/pulls
    about: Pull request for documentations
  - name: ğŸ”— Middlewares
    url: https://github.com/nanoexpress/middlewares/pulls
    about: Pull request for middlewares
